### ISSUE TITLE
[Feature Request] Ability to anchor to silly or serious when sharing the URL

### ISSUE THREAD

**Issue by misslivirose** [zfox23/iamagoodbing#3]
This way if you wanted to share the link to the site to default to one of those, you could (e.g. iamagoodbing.ai#serious)

**Comment by zfox23** [comment]
Implemented! Examples:
- https://www.iamagoodbing.ai/#goodbing
- https://www.iamagoodbing.ai/#ftc-watching

Great idea :)

**Comment by zfox23** [comment]
OH WAIT NOT IMPLEMENTED. you can link to stories specifically, but being able to link to the entire section is a good idea.

**Comment by zfox23** [comment]
IMPLEMENTED!
