### ISSUE TITLE
Future of Life calls for Pausing AI Experiments; White Men Get Credit for Things Timnit Gebru Has Been Saying For Years

### ISSUE THREAD

**Issue by misslivirose** [zfox23/iamagoodbing#5]
Link: https://futureoflife.org/open-letter/pause-giant-ai-experiments/

Text: 

Today, Future of Life announced an open letter signed by big names in tech calling on AI to slow down until we can understand the implications of what it means for human life. On the surface, this seems like a good thing, but I have a lot of skepticism. First of all, the fact that Elon Musk is now getting credit for this call to action instead of someone like Timnit Gebru, who has been advocating for more intentional and ethical building of artificial intelligence for years, is a gross example of how white men continue to get listened to when Black women are pushed out of jobs for saying the same thing. It's gross, racist, and I'm mad about how publications are reporting on this. Future of Life's Board and team are... not exactly diverse, and here they are getting credit for all agreeing on something that Gebru and Dr. Fei-Fei Li have been working on for the past five years.

Second of all, this almost reads like code for "Slow Down AI... so our Other Company Can Catch Up". This would be a stronger message coming from regulators than people who stand to continue to benefit from their tech infrastructure getting a chance to understand how to take on Microsoft and Google.

I'm sure that this has everything to do with benevolence, and nothing at all with the way that Wall Street erased 33% of FAANG market cap in 2022.

**Comment by misslivirose** [comment]
https://www.dair-institute.org/ - Timnit Gebru's new research organization
https://en.wikipedia.org/wiki/Timnit_Gebru
https://en.wikipedia.org/wiki/Fei-Fei_Li
https://ai-4-all.org/ - AI 4 All is Dr. Li's nonprofit

**Comment by zfox23** [comment]
implementing this now - thank you so much for your submission!
